from pathlib import Path
from typing import Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from langgraph.types import Command

import config
from agents.career_agent import career_agent, reset_agent_thread_memory
from graphs.resume_editor_graph import resume_editor_graph, reset_editor_thread_memory
from services.resume_service import (
    has_original_backup,
    restore_original_resume
)
from vectorstore import reindex_active_resume

router = APIRouter()

class CopilotChatRequest(BaseModel):
    message: str
    thread_id: str

class ProviderToggleRequest(BaseModel):
    provider: str

class ResumeActionRequest(BaseModel):
    thread_id: str
    action: str  # "approve", "reject", "cancel"
    feedback: Optional[str] = None

class ResumeRevertRequest(BaseModel):
    thread_id: Optional[str] = None


@router.post("/chat")
@router.post("/copilot/chat")
async def chat_copilot(request: CopilotChatRequest):
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")
    if not request.thread_id.strip():
        raise HTTPException(status_code=400, detail="Thread ID cannot be empty")

    thread_conf = {"configurable": {"thread_id": request.thread_id}}

    try:
        print(f"\n💬 [COPILOT CHAT] Thread ID: '{request.thread_id}' | Provider: {config.LLM_PROVIDER.upper()}")
        print(f"👤 [USER INPUT]  '{request.message}'")

        # 1. Check if there is an active interrupted resume edit awaiting human review
        edit_state = resume_editor_graph.get_state(thread_conf)
        if edit_state and edit_state.tasks and any(t.interrupts for t in edit_state.tasks):
            user_msg = request.message.lower().strip()
            # Determine human action from message
            if user_msg in ["approve", "approved", "yes", "accept", "apply", "looks good", "do it", "sure", "ok"]:
                action = "approve"
                feedback = None
            elif user_msg in ["cancel", "stop", "abort", "nevermind", "no"]:
                action = "cancel"
                feedback = None
            else:
                action = "reject"
                feedback = request.message

            result = resume_editor_graph.invoke(Command(resume={"action": action, "feedback": feedback}), config=thread_conf)
            updated_state = resume_editor_graph.get_state(thread_conf)

            # If it cycled back to an interrupt (proposal updated)
            if updated_state.tasks and any(t.interrupts for t in updated_state.tasks):
                interrupt_val = updated_state.tasks[0].interrupts[0].value
                return {
                    "message": "I have adjusted the proposed changes based on your feedback. Please review:",
                    "type": "resume_edit_proposal",
                    "target_original": interrupt_val.get("target_original"),
                    "proposed_diff": interrupt_val.get("proposed_diff"),
                    "explanation": interrupt_val.get("explanation"),
                    "thread_id": request.thread_id,
                    "provider": config.LLM_PROVIDER,
                    "can_revert": has_original_backup()
                }

            # If completed or cancelled
            return {
                "message": result.get("message", "Resume edit finished."),
                "type": "resume_edit_result",
                "status": result.get("status"),
                "thread_id": request.thread_id,
                "provider": config.LLM_PROVIDER,
                "can_revert": has_original_backup(),
                "download_url": "/copilot/resume/download" if result.get("status") == "completed" else None
            }

        # 2. Copilot conversational agent execution with tools and memory checkpointer
        result = career_agent.invoke(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": request.message
                    }
                ]
            },
            config=thread_conf
        )

        messages = result.get("messages", [])
        for msg in messages:
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                for tc in msg.tool_calls:
                    print(f"🛠️  [AGENT INITIATED TOOL] Name: {tc.get('name')} | Args: {tc.get('args')}")

        response_text = messages[-1].content if messages else "No response generated by Copilot agent."

        # 3. Check if the agent called the propose_resume_edit tool and paused for review
        edit_state = resume_editor_graph.get_state(thread_conf)
        if edit_state and edit_state.tasks and any(t.interrupts for t in edit_state.tasks):
            interrupt_val = edit_state.tasks[0].interrupts[0].value
            return {
                "message": response_text or "I've prepared a proposed update for your resume. Please review the diff below:",
                "type": "resume_edit_proposal",
                "target_original": interrupt_val.get("target_original"),
                "proposed_diff": interrupt_val.get("proposed_diff"),
                "explanation": interrupt_val.get("explanation"),
                "thread_id": request.thread_id,
                "provider": config.LLM_PROVIDER,
                "can_revert": has_original_backup()
            }

        return {
            "message": response_text,
            "thread_id": request.thread_id,
            "provider": config.LLM_PROVIDER,
            "can_revert": has_original_backup()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/resume/action")
@router.post("/copilot/resume/action")
async def handle_resume_action(request: ResumeActionRequest):
    """
    Direct endpoint for frontend action buttons (Approve, Reject, Cancel)
    """
    thread_conf = {"configurable": {"thread_id": request.thread_id}}

    try:
        edit_state = resume_editor_graph.get_state(thread_conf)
        if not edit_state or not edit_state.tasks or not any(t.interrupts for t in edit_state.tasks):
            raise HTTPException(status_code=400, detail="No active resume edit proposal found waiting for review.")

        result = resume_editor_graph.invoke(
            Command(resume={"action": request.action, "feedback": request.feedback}),
            config=thread_conf
        )

        updated_state = resume_editor_graph.get_state(thread_conf)
        if updated_state.tasks and any(t.interrupts for t in updated_state.tasks):
            interrupt_val = updated_state.tasks[0].interrupts[0].value
            return {
                "message": "I have adjusted the proposed changes based on your feedback. Please review:",
                "type": "resume_edit_proposal",
                "target_original": interrupt_val.get("target_original"),
                "proposed_diff": interrupt_val.get("proposed_diff"),
                "explanation": interrupt_val.get("explanation"),
                "thread_id": request.thread_id,
                "provider": config.LLM_PROVIDER,
                "can_revert": has_original_backup()
            }

        return {
            "message": result.get("message", "Resume edit processed."),
            "type": "resume_edit_result",
            "status": result.get("status"),
            "thread_id": request.thread_id,
            "provider": config.LLM_PROVIDER,
            "can_revert": has_original_backup(),
            "download_url": "/copilot/resume/download" if result.get("status") == "completed" else None
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/resume/revert")
@router.post("/copilot/resume/revert")
async def revert_resume(request: Optional[ResumeRevertRequest] = None):
    """
    Reverts the active resume back to the original uploaded version,
    re-indexes the vector store, and clears stale agent/editor memory for the thread.
    """
    try:
        restore_original_resume()
        num_chunks = reindex_active_resume()

        thread_id = request.thread_id if request else None
        if thread_id:
            reset_agent_thread_memory(thread_id)
            reset_editor_thread_memory(thread_id)
            # Seed a clean event in the thread so future LLM reasoning is grounded
            try:
                career_agent.invoke(
                    {
                        "messages": [
                            {
                                "role": "user",
                                "content": (
                                    "[SYSTEM EVENT]: The candidate has reverted their resume to the original version. "
                                    "All previous edits or additions have been discarded. "
                                    "Active resume is now strictly the original resume."
                                )
                            }
                        ]
                    },
                    config={"configurable": {"thread_id": thread_id}}
                )
            except Exception as e:
                print(f"[WARN] Failed to seed revert notice: {e}")

        return {
            "message": "Successfully reverted to your original resume. Conversation context and memory have been refreshed.",
            "reverted": True,
            "num_chunks": num_chunks
        }
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/resume/version-status")
@router.get("/copilot/resume/version-status")
async def get_version_status():
    """
    Returns whether the resume has an original backup available to revert to.
    """
    return {
        "can_revert": has_original_backup()
    }


@router.get("/resume/download")
@router.get("/copilot/resume/download")
async def download_resume():
    """
    Allows user to download the current active resume PDF.
    """
    resume_path = Path(config.UPLOAD_DIR) / "resume.pdf"
    if not resume_path.exists():
        raise HTTPException(status_code=404, detail="Resume not found")

    return FileResponse(
        path=str(resume_path),
        filename="AI_Career_Copilot_Resume.pdf",
        media_type="application/pdf"
    )


@router.get("/resume-status")
@router.get("/copilot/resume-status")
async def get_resume_status():
    resume_path = Path(config.UPLOAD_DIR) / "resume.pdf"
    exists = resume_path.exists()
    return {
        "uploaded": exists,
        "filename": "resume.pdf" if exists else None,
        "can_revert": has_original_backup()
    }


@router.get("/provider")
@router.get("/copilot/provider")
async def get_provider():
    return {
        "provider": config.LLM_PROVIDER,
        "model": config.GROQ_MODEL if config.LLM_PROVIDER == "cloud" else config.LLM_MODEL
    }


@router.post("/provider")
@router.post("/copilot/provider")
async def set_provider(request: ProviderToggleRequest):
    prov = request.provider.strip().lower()
    target_provider = "cloud" if prov in ["cloud", "groq"] else "local"

    from services.llm_service import get_llm
    old_provider = config.LLM_PROVIDER
    try:
        # Validate that the selected provider can be instantiated
        config.LLM_PROVIDER = target_provider
        _ = get_llm()
        # Invalidate agent cache so it rebuilds with the new model
        career_agent.reset_agent()
    except Exception as e:
        config.LLM_PROVIDER = old_provider
        raise HTTPException(status_code=400, detail=str(e))

    return {
        "provider": config.LLM_PROVIDER,
        "model": config.GROQ_MODEL if config.LLM_PROVIDER == "cloud" else config.LLM_MODEL
    }
