from pathlib import Path
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

import config
from agents.career_agent import career_agent
from services.llm_service import clean_llm_output

router = APIRouter()

class CopilotChatRequest(BaseModel):
    message: str
    thread_id: str

class ProviderToggleRequest(BaseModel):
    provider: str

@router.post("/chat")
@router.post("/copilot/chat")
async def chat_copilot(request: CopilotChatRequest):
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")
    if not request.thread_id.strip():
        raise HTTPException(status_code=400, detail="Thread ID cannot be empty")

    try:
        print(f"\n💬 [COPILOT CHAT] Thread ID: '{request.thread_id}' | Provider: {config.LLM_PROVIDER.upper()}")
        print(f"👤 [USER INPUT]  '{request.message}'")

        result = career_agent.invoke(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": request.message
                    }
                ]
            },
            config={"configurable": {"thread_id": request.thread_id}}
        )

        messages = result.get("messages", [])
        for msg in messages:
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                for tc in msg.tool_calls:
                    print(f"🛠️  [AGENT INITIATED TOOL] Name: {tc.get('name')} | Args: {tc.get('args')}")

        if not messages:
            response_text = "No response generated by Copilot agent."
        else:
            response_text = clean_llm_output(messages[-1].content)

        return {
            "message": response_text,
            "thread_id": request.thread_id,
            "provider": config.LLM_PROVIDER
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/resume-status")
@router.get("/copilot/resume-status")
async def get_resume_status():
    resume_path = Path(config.UPLOAD_DIR) / "resume.pdf"
    exists = resume_path.exists()
    return {
        "uploaded": exists,
        "filename": "resume.pdf" if exists else None
    }

@router.get("/provider")
@router.get("/copilot/provider")
async def get_provider():
    return {
        "provider": config.LLM_PROVIDER,
        "model": config.GROQ_MODEL if config.LLM_PROVIDER == "cloud" else config.LLM_MODEL
    }

@router.post("/provider")
@router.post("/copilot/provider")
async def set_provider(request: ProviderToggleRequest):
    prov = request.provider.strip().lower()
    if prov in ["cloud", "groq"]:
        config.LLM_PROVIDER = "cloud"
    else:
        config.LLM_PROVIDER = "local"

    # Re-link current LLM to agent if needed
    from services.llm_service import get_llm
    try:
        new_llm = get_llm()
        career_agent.model = new_llm
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

    return {
        "provider": config.LLM_PROVIDER,
        "model": config.GROQ_MODEL if config.LLM_PROVIDER == "cloud" else config.LLM_MODEL
    }
